# Site settings
title: "Unit1337"
bye_message: "É nós que pwna hackudão!"
baseurl: "/leet"
url: "http://unit1337.github.io/"
# disqus: gjuniioor

# Header settings
nick: "Unit1337"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "unit1337"
# blog:
#     server: "wordpress.com"
#     nick: "gjuniioor"
# fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
