# Site settings
title: "Unit1337"
bye_message: "É nós que pwna hackudão!"
baseurl: "https://unit1337.github.io/"
url: "http://unit1337.github.io/"
# disqus: gjuniioor

# Header settings
nick: "Unit1337"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "unit1337"
# blog:
#     server: "wordpress.com"
#     nick: "gjuniioor"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
